#[cfg(feature = "derive")]
pub use struct_to_enum_macros::*;

/// Implemented by structs that have a `FieldName` enum generated by the `struct-to-enum-macros` crate.
///
/// - `N` is the number of non-skipped fields (a compile-time constant)
///
/// Deriving `FieldName` on a struct `Foo` generates:
///
/// ```ignore
/// impl FieldNames<N> for Foo { ... }
/// ```
///
/// which allows calling `foo.field_names()` to obtain an ordered array of all field-name variants.
pub trait FieldNames<const N: usize> {
    type FieldName;

    // can't use const generics in trait bounds yet (requires nightly)
    // #![feature(generic_const_exprs)]
    // const N: usize;

    /// Returns all field-name enum variants in field declaration order.
    ///
    /// NOTE: This method will be made `const` once `const_trait_impl` is stabilised.
    /// Tracking issue: <https://github.com/rust-lang/rust/issues/67792>
    fn field_names() -> [Self::FieldName; N];
}

#[cfg(test)]
mod tests {
    use crate::FieldNames;

    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Test {
        pub a: i32,
        pub b: i32,
    }

    #[derive(Debug, PartialEq, Clone, Copy)]
    pub enum TestFieldName {
        A,
        B,
    }

    impl FieldNames<2> for Test {
        type FieldName = TestFieldName;
        fn field_names() -> [Self::FieldName; 2] {
            [TestFieldName::A, TestFieldName::B]
        }
    }

    #[test]
    pub fn test_field_names() {
        let _test = Test { a: 0, b: 0 };
        let _a: TestFieldName = <Test as FieldNames<2>>::FieldName::A;
        assert_eq!(Test::field_names(), [TestFieldName::A, TestFieldName::B]);
    }
}
