name: CI & Tests

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - ci-*

env:
  RUST_TOOLCHAIN: "1.85.0" # Should be the same as in the crate

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace -- -D warnings
      - run: cargo clippy --workspace --features nested-type,nested-name -- -D warnings

  rustfmt:
    name: Rust-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test:
    name: Test ${{ matrix.features }} (stable)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - features: "no features"
            flags: ""
          - features: "nested-type"
            flags: "--features nested-type"
          - features: "nested-name"
            flags: "--features nested-name"
          - features: "nested-type,nested-name"
            flags: "--features nested-type,nested-name"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build workspace
        run: cargo build --workspace --verbose ${{ matrix.flags }}
      - name: Run tests
        run: cargo test --workspace --verbose ${{ matrix.flags }}

  msrv:
    name: MSRV ${{ matrix.features }} (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: "1.85.0"
            features: "no features"
            flags: ""
          - toolchain: "1.85.0"
            features: "nested-type,nested-name"
            flags: "--features nested-type,nested-name"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - name: Build workspace
        run: cargo build --workspace --verbose ${{ matrix.flags }}
      - name: Run tests
        run: cargo test --workspace --verbose ${{ matrix.flags }}
